version: '3'

services:
  php:
    container_name: php-test
    image: php-test
    ports:
      - "8080:80"
    restart: always
#    environment:
#      - JAEGER_SERVICE_NAME=service
#      - JAEGER_AGENT_HOST=jaeger
#      - JAEGER_AGENT_PORT=6831
#      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
  jaeger:
    image: jaegertracing/all-in-one:1.49
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4318:4318"
      - "4317:4317"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    restart: always

networks:
  default:
    name: jaeger
    external: true
